---
- name: Base configuration
  hosts: linux
  become: true
  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install dependancies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl

    - name: Install keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Curl keyring
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Change keyring permission
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0444'
    
    - name: Remove old docker sources if exists
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.sources
        state: absent

    - name: Add docker repositiories to repo source folder
      ansible.builtin.template:
        src: "{{ files_dir }}/docker.sources.j2"
        dest: "/etc/apt/sources.list.d/docker.sources"
        mode: '0644'

    - name: apt update after adding docker repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

